"""Setup DB

Revision ID: 207b43fc3d28
Revises: 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207b43fc3d28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('shortened_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_shortened_url'), 'short_url', ['shortened_url'], unique=True)
    # ### end Alembic commands ###

    with open("sql/random_url_trigger.sql", "r") as sql_file:
        op.execute(sql_file.read().replace('\n', ' '))


def downgrade():
    op.execute('DROP TRIGGER IF EXISTS gen_random_url ON short_url;')
    op.execute('DROP FUNCTION IF EXISTS random_string(integer);')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_shortened_url'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###

